version: '2'
services:

  php5_3:
    container_name: php5_3
    build: .
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/www:/var/www
      - ./volumes/conf.d:/usr/local/etc/php/conf.d

