version: '2.3'
services:

  php5_3:
    container_name: php5_3
    user: "${WWWUID}:${WWWGID}"
    build:
      context: .
      args:
        UNAME: ${WWWUNAME}
        UID: ${WWWUID}
        GID: ${WWWGID}
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/www:/var/www
      - ./volumes/conf.d:/usr/local/etc/php/conf.d
      - ./volumes/php-fpm-log:/usr/local/etc/php/var/log
